// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBImwJhLGRa-X6zM4_fkq9yH8eECf3c5Is',
    appId: '1:605052386476:web:2bc45d3da007dbd5357309',
    messagingSenderId: '605052386476',
    projectId: 'login-82fa9',
    authDomain: 'login-82fa9.firebaseapp.com',
    storageBucket: 'login-82fa9.appspot.com',
    measurementId: 'G-G3E0T1ZS9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC0pCYmU--7Su8p6JevRJZEMtQ0wy9HZE',
    appId: '1:605052386476:android:5419efe52fe1313a357309',
    messagingSenderId: '605052386476',
    projectId: 'login-82fa9',
    storageBucket: 'login-82fa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZRJSrPOYyCawjpRfYR9obcZ1bO-k7FBQ',
    appId: '1:605052386476:ios:dd8fe76101ff10e1357309',
    messagingSenderId: '605052386476',
    projectId: 'login-82fa9',
    storageBucket: 'login-82fa9.appspot.com',
    iosClientId: '605052386476-r2v3umjpuapes768dtc7f88um7s5ft05.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginbloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZRJSrPOYyCawjpRfYR9obcZ1bO-k7FBQ',
    appId: '1:605052386476:ios:dd8fe76101ff10e1357309',
    messagingSenderId: '605052386476',
    projectId: 'login-82fa9',
    storageBucket: 'login-82fa9.appspot.com',
    iosClientId: '605052386476-r2v3umjpuapes768dtc7f88um7s5ft05.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginbloc',
  );
}
